local DataStorage = require("datastorage")
local UIManager = require("ui/uimanager")
local InfoMessage = require("ui/widget/infomessage")
local FileManager = require("apps/filemanager/filemanager")
local _ = require("qiqiappstore_gettext")
local Net = require("qiqiappstore_net")
local util = require("util")
local logger = require("logger")
local lfs = require("libs/libkoreader-lfs")
local Version = require("version")
local Mirror = require("qiqiappstore_mirror")
local Policy = require("qiqiappstore_policy")

local RepoContent = {}

-- TextViewer only gained Markdown rendering (text_format = "md") in KOReader
-- v2026.07. Older versions keep the cache-to-file-then-open flow below.
local README_POPUP_MIN_VERSION = Version:getNormalizedVersion("v2026.07")
function RepoContent.supportsReadmePopup()
    return (Version:getNormalizedCurrentVersion() or 0) >= README_POPUP_MIN_VERSION
end

local function getCacheDir()
    local dir = DataStorage:getDataDir() .. "/cache/qiqiappstore/readme"
    local ok, err = util.makePath(dir)
    if not ok then
        logger.warn("QiqiAppStore README cache dir failure", err)
    end
    return dir
end

local function buildRawUrl(owner, repo)
    return string.format("https://raw.githubusercontent.com/%s/%s/HEAD/README.md", owner, repo)
end

local function getCachePath(owner, repo)
    if not Policy.allows(owner, repo) then
        return nil, "repository is outside the QiqiAppStore account policy"
    end
    -- Policy already restricts both values to a safe literal account and a
    -- filename-safe repository name. Keep legal dots so a.b and a_b never
    -- collapse onto the same cache entry.
    local filename = string.format("%s__%s__README.md", owner:lower(), repo)
    return getCacheDir() .. "/" .. filename
end

local function download(url)
    local response = {}
    -- This runs on the UI thread: a connection that never answers would otherwise hold the
    -- interface until KOReader is restarted.
    local code, _, status = Net.requestToTable({
        url = url,
        headers = {
            ["Accept"] = "text/plain",
            ["User-Agent"] = "KOReader-QiqiAppStore",
        },
    }, response)
    -- A timeout arrives as a string in place of a status; a throw leaves nothing there at
    -- all and its reason in `status`. Kept apart, so the caller can tell one from the other.
    return code, status, table.concat(response)
end

-- Download and clean the raw README body, shared by the cached and
-- direct-to-viewer fetch paths below.
local function downloadReadmeBody(owner, repo)
    if not Policy.allows(owner, repo) then
        return nil, "repository is outside the QiqiAppStore account policy"
    end
    local url = Mirror.apply(buildRawUrl(owner, repo))
    local code, status, body = download(url)
    -- Same rule as fetchGitHubRaw: a throw has no code, and its reason is not HTTP.
    if tonumber(code) ~= 200 then
        if code then
            return nil, string.format("HTTP %s", tostring(code))
        end
        return nil, tostring(status or "network error")
    end
    if not body or body == "" then
        return nil, "empty body"
    end
    -- Strip inline HTML <img> tags to avoid rendering issues in the text viewer.
    -- This keeps the textual README content while dropping embedded images.
    body = body:gsub("<img[^>]->", "")
    return body
end

function RepoContent.readCachedReadme(owner, repo)
    local path, path_err = getCachePath(owner, repo)
    if not path then return nil, path_err end
    local content = util.readFromFile(path)
    if not content or content == "" then return nil, "cached README not found" end
    return content, path
end

local function fetchAndCacheReadme(owner, repo)
    local path, path_err = getCachePath(owner, repo)
    if not path then return nil, nil, path_err end

    local body, download_err = downloadReadmeBody(owner, repo)
    if body then
        local ok, write_err = util.writeToFile(body, path)
        if not ok then return nil, nil, write_err or "write error" end
        return body, path
    end

    local cached, cached_path = RepoContent.readCachedReadme(owner, repo)
    if cached then return cached, cached_path end
    return nil, nil, download_err
end

-- Legacy path (KOReader older than TextViewer markdown support): download the
-- README and cache it to disk, returning the file path.
function RepoContent.fetchReadme(owner, repo)
    local body, path, err = fetchAndCacheReadme(owner, repo)
    if not body then
        return false, err
    end
    return true, path
end

-- Direct-to-viewer path shares the same on-disk cache as the legacy file flow.
function RepoContent.fetchReadmeContent(owner, repo)
    local body, _, err = fetchAndCacheReadme(owner, repo)
    return body, err
end

-- Remove every cached README markdown file generated by RepoContent.fetchReadme.
-- Returns a table with `removed` count and `errors` list (failed file paths).
function RepoContent.clearReadmeCache()
    local dir = DataStorage:getDataDir() .. "/cache/qiqiappstore/readme"
    local removed = 0
    local errors = {}
    if lfs.attributes(dir, "mode") ~= "directory" then
        return { removed = 0, errors = errors }
    end
    for entry in lfs.dir(dir) do
        if entry ~= "." and entry ~= ".." then
            local full_path = dir .. "/" .. entry
            local mode = lfs.attributes(full_path, "mode")
            if mode == "file" then
                local ok = os.remove(full_path)
                if ok then
                    removed = removed + 1
                else
                    table.insert(errors, full_path)
                end
            end
        end
    end
    return { removed = removed, errors = errors }
end

function RepoContent.openReadme(path)
    if not path then
        UIManager:show(InfoMessage:new{ text = _("Missing README path"), timeout = 4 })
        return
    end
    local text, err = util.readFromFile(path)
    if not text or text == "" then
        UIManager:show(InfoMessage:new{ text = _("Unable to read README file"), timeout = 4 })
        return
    end
    FileManager:openFile(path)
end

return RepoContent
